/**
 * @crewhaus/ui — shape detection + local-runner scaffolding.
 *
 * Given a directory that holds a compiled CrewHaus harness (and usually its
 * `crewhaus.yaml`), figure out which shape it is and write a tiny local file
 * that imports `@crewhaus/ui` and serves the matching UI.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";

/** Package root = the dir that holds `_shared/` and every `<shape>/`. */
export const PKG_ROOT = resolve(import.meta.dir, "..");

/** Every shape the package ships (a dir with a config.json). */
export function listShapes(): string[] {
  return readdirSync(PKG_ROOT)
    .filter(
      (n) =>
        n !== "_shared" &&
        !n.startsWith(".") &&
        n !== "src" &&
        n !== "bin" &&
        n !== "node_modules" &&
        existsSync(join(PKG_ROOT, n, "config.json")),
    )
    .sort();
}

/** Read the top-level `target:` from a spec in `dir` (lightweight, no YAML dep). */
export function readSpecTarget(dir: string): string | null {
  if (!existsSync(dir)) return null;
  const seen = new Set(["crewhaus.yaml", "crewhaus.yml"]);
  for (const f of readdirSync(dir)) if (/\.ya?ml$/.test(f)) seen.add(f);
  for (const name of seen) {
    const p = join(dir, name);
    if (!existsSync(p)) continue;
    const m = readFileSync(p, "utf8").match(
      /^\s*target:\s*["']?([A-Za-z0-9_-]+)["']?\s*(?:#.*)?$/m,
    );
    if (m) return m[1];
  }
  return null;
}

/**
 * Detect the shape of a compiled harness directory. Returns a shape name the
 * package knows, or null if it can't tell (caller should ask for `--shape`).
 */
export function detectShape(dir: string): string | null {
  const has = (p: string) => existsSync(join(dir, p));
  const shapes = new Set(listShapes());

  // Claude plugin bundles carry a manifest, never a runnable entry.
  if (has(".claude-plugin/plugin.json") || has(".claude-plugin")) return "claude-plugin";

  const target = readSpecTarget(dir);

  // A worker.js + wrangler.toml is a Cloudflare emit of a cli/graph/workflow spec.
  if (has("worker.js") && has("wrangler.toml")) {
    const cand = target ? `cf-worker-${target}` : "cf-worker-cli";
    return shapes.has(cand) ? cand : "cf-worker-cli";
  }

  // Otherwise the spec's target maps 1:1 to a shape.
  if (target && shapes.has(target)) return target;
  return null;
}

/** Pick the harness dir: explicit, else cwd if it has a bundle, else ./build. */
export function resolveHarnessDir(explicit: string | undefined, cwd: string): string {
  if (explicit) return resolve(cwd, explicit);
  const looksCompiled = (d: string) =>
    existsSync(d) &&
    ["agent.ts", "daemon.ts", "worker.js", ".claude-plugin"].some((f) => existsSync(join(d, f)));
  if (looksCompiled(cwd)) return resolve(cwd);
  const build = join(cwd, "build");
  if (looksCompiled(build)) return build;
  const dist = join(cwd, "dist");
  if (looksCompiled(dist)) return dist;
  return resolve(cwd);
}

export type ScaffoldOptions = {
  shape: string;
  harnessDir: string;
  outFile: string;
  port?: number;
  force?: boolean;
};

/** Write a local runner that imports `@crewhaus/ui`. Returns its absolute path. */
export function scaffold(opts: ScaffoldOptions): string {
  const out = resolve(opts.outFile);
  if (existsSync(out) && !opts.force) {
    throw new Error(`${opts.outFile} already exists — pass --force to overwrite`);
  }
  let rel = relative(dirname(out), resolve(opts.harnessDir));
  if (rel === "") rel = ".";
  const usesJoin = rel !== ".";
  const harnessExpr = usesJoin ? `join(import.meta.dir, ${JSON.stringify(rel)})` : "import.meta.dir";
  const lines = [
    "#!/usr/bin/env bun",
    `// Generated by @crewhaus/ui — serves the "${opts.shape}" UI for this harness.`,
    `// Run:  bun ${basename(out)}`,
    usesJoin ? 'import { join } from "node:path";' : null,
    'import { serve } from "@crewhaus/ui";',
    "",
    "serve({",
    `  shape: ${JSON.stringify(opts.shape)},`,
    `  harnessDir: ${harnessExpr},`,
    opts.port ? `  port: ${opts.port},` : null,
    "});",
    "",
  ].filter((l): l is string => l !== null);
  writeFileSync(out, lines.join("\n"));
  return out;
}
